/**
 * This Activity can be called from three different ones.
 * Threre fore there are 2 control flags to know from whom is called.
 * -hasChanges: Home and Detail vs. Change Autogenerated 
 * -id: Home(==0) vs Detail(>0)
 */

package com.loopback.androidapps.saveapp;

import android.app.Activity;
import android.content.Intent;
import android.os.Bundle;
import android.text.InputType;
import android.util.Log;
import android.view.View;
import android.widget.ArrayAdapter;
import android.widget.AutoCompleteTextView;
import android.widget.Button;
import android.widget.EditText;
import android.widget.ImageButton;
import android.widget.TextView;
import android.widget.Toast;

public class OutlayEditActivity extends Activity implements
		View.OnClickListener {

	private ImageButton btnPhoto, btnNotes, btnFile;
	private Button btnAccept, btnAddressChange;
	private EditText edtCharge;
	private AutoCompleteTextView edtItem, edtPlace;
	private TextView txtAccount, txtAddress, txtDate;
	private Outlay outlay;
	private String note, date, item, place, album, addressDesc, receivedDate,
			receivedAddressDesc;
	public boolean isAdding, receivedHasChanges;
	private double latitude, longitude, receivedLatitude, receivedLongitude;
	private int charge = 0, receivedId = 0, addressId = 1;
	public static String NOTE, ADDRESS_DESC;

	public SaveApp saveApp;

	/*------------------------------------------------------------------------------------------------
	 *--------------------------------------ONCREATE--------------------------------------------------
	 *------------------------------------------------------------------------------------------------ */

	public void onCreate(Bundle savedInstanceState) {
		Log.i("OEA", "Init");
		super.onCreate(savedInstanceState);
		setContentView(R.layout.editoutlay);
		loadActivity();
	}

	/*------------------------------------------------------------------------------------------------
	 *--------------------------------------LOAD--------------------------------------------------
	 *------------------------------------------------------------------------------------------------ */
	public void loadActivity() {

		Log.i("OEA", "Loading...");
		saveApp = ((SaveApp) getApplicationContext());

		note = null;
		btnPhoto = (ImageButton) findViewById(R.id.btnPhoto);
		btnNotes = (ImageButton) findViewById(R.id.btnNotes);
		btnFile = (ImageButton) findViewById(R.id.btnFile);
		btnAccept = (Button) findViewById(R.id.btnAccept);
		btnAddressChange = (Button) findViewById(R.id.btnAddressChange);
		edtCharge = (EditText) findViewById(R.id.edtCharge);
		edtItem = (AutoCompleteTextView) findViewById(R.id.edtItem);
		edtPlace = (AutoCompleteTextView) findViewById(R.id.edtPlace);
		txtAccount = (TextView) findViewById(R.id.txtAccount);
		txtAddress = (TextView) findViewById(R.id.txtAddress);
		txtDate = (TextView) findViewById(R.id.txtDate);

		edtItem.setInputType(InputType.TYPE_TEXT_FLAG_CAP_WORDS);
		edtPlace.setInputType(InputType.TYPE_TEXT_FLAG_CAP_WORDS);

		btnPhoto.setOnClickListener(this);
		btnNotes.setOnClickListener(this);
		btnFile.setOnClickListener(this);
		btnAccept.setOnClickListener(this);
		btnAddressChange.setOnClickListener(this);

	}

	/*------------------------------------------------------------------------------------------------
	 *--------------------------------------ONRESUME--------------------------------------------------
	 *------------------------------------------------------------------------------------------------ */

	public void onResume() {
		super.onResume();
		restoreState();
		settings();
	}

	public void restoreState() {
		// Load Autocomplete items
		final String[] items;
		Item itemAutoComplete = new Item();
		items = itemAutoComplete.selectItems();
		ArrayAdapter<String> adapterItems = new ArrayAdapter<String>(this,
				R.layout.autocompleteitem, items);
		edtItem.setAdapter(adapterItems);
		edtItem.setThreshold(1);

		final String[] places;
		Place placeAutoComplete = new Place();
		places = placeAutoComplete.selectPlaces();
		ArrayAdapter<String> adapterPlaces = new ArrayAdapter<String>(this,
				R.layout.autocompleteplace, places);
		edtPlace.setAdapter(adapterPlaces);
		edtPlace.setThreshold(1);

		charge = saveApp.outlay.getCharge();
		item = saveApp.outlay.getItemDesc();
		place = saveApp.outlay.getPlaceDesc();
		note = saveApp.outlay.getNote();
		date = saveApp.outlay.getDate();
		addressDesc = saveApp.outlay.getAddressDesc();
		latitude = saveApp.getLatitude();
		longitude = saveApp.getLongitude();

		edtCharge.setText(String.valueOf(charge));
		edtItem.setText(item);
		edtPlace.setText(place);
		txtDate.setText(date);
		txtAddress.setText(addressDesc);
		txtAccount.setText(getString(R.string.strAccount) + ": "
				+ saveApp.getAccountDesc());
	}

	/*------------------------------------------------------------------------------------------------
	 *--------------------------------------ONPAUSE--------------------------------------------------
	 *------------------------------------------------------------------------------------------------ */

	public void onPause() {
		saveState();
		super.onPause();
	}

	public void saveState() {
		charge = Utilities.stringToInt(edtCharge.getText().toString());
		item = edtItem.getText().toString();
		place = edtPlace.getText().toString();
		album = "";
		addressDesc = txtAddress.getText().toString();
		date = txtDate.getText().toString();

		saveApp.outlay.setCharge(charge);
		saveApp.outlay.setItemDesc(item);
		saveApp.outlay.setPlaceDesc(place);
		saveApp.outlay.setNote(note);
		saveApp.outlay.setAlbumId(1);
		saveApp.outlay.setDate(date);
		saveApp.outlay.setAddressDesc(addressDesc);
		saveApp.setLatitude(latitude);
		saveApp.setLongitude(longitude);
	}

	/*------------------------------------------------------------------------------------------------
	 *--------------------------------------GET DATA FROM PREVIOUS ACTIVITY---------------------------
	 *------------------------------------------------------------------------------------------------ */
	public void settings() {
		// Initialize variables

		/*-------------------------------------- GET DATA -----------------------------*/

		Bundle bundle = this.getIntent().getExtras();
		receivedHasChanges = bundle.getBoolean("HasChanges");

		/*--------------------------------------FROM CHANGE AUTOGENERATED-----------------------------*/

		if (receivedHasChanges) {
			isAdding = saveApp.isAdding();
			receivedId = bundle.getInt("Id");
			receivedDate = bundle.getString("Date");
			receivedAddressDesc = bundle.getString("AddressDesc");
			receivedLatitude = bundle.getDouble("Latitude");
			receivedLongitude = bundle.getDouble("Longitude");

			// Get Received Data
			date = receivedDate;
			addressDesc = receivedAddressDesc;
			latitude = receivedLatitude;
			longitude = receivedLongitude;

			// Set Received Data
			txtAddress.setText((addressDesc == null) ? "No data" : addressDesc);
			txtDate.setText(date);

		} else {
			// The previous activity is Home or DetailOutlay
			isAdding = saveApp.isAdding();
			receivedId = bundle.getInt("Id");

			/*--------------------------------------FROM DETAIL-----------------------------------------*/
			// if (receivedId > 0) {
			// outlay = new Outlay(receivedId);
			//
			// addressDesc = outlay.getAddressDesc();
			//
			// edtCharge.setText(String.valueOf(outlay.getCharge()));
			// edtItem.setText(outlay.getItemDesc());
			// edtPlace.setText(outlay.getPlaceDesc());
			//
			// txtAccount.setText(getString(R.string.strAccount) + ": "
			// + saveApp.getAccountDesc());
			//
			// txtAddress.setText(addressDesc);
			// txtDate.setText(date);

			/*--------------------------------------FROM HOME-----------------------------------------*/
			// } else {
			// // Get Today Date
			// saveApp.setDate(Utilities.dateGetter());
			//
			// // Set Global Variables
			// date = saveApp.getDate();
			// addressDesc = saveApp.getAddressDesc();
			// latitude = saveApp.getLatitude();
			// longitude = saveApp.getLongirude();
			//
			// // Set Activity texts
			// txtAccount.setText(getString(R.string.strAccount) + ": "
			// + saveApp.getAccountDesc());
			// txtAddress.setText((addressDesc == null) ? "No data"
			// : addressDesc);
			// txtDate.setText(date);
			// Log.i("OEA", "Loaded");
			// }
		}

	}

	/*------------------------------------------------------------------------------------------------
	 *--------------------------------------ONBACK--------------------------------------------------
	 *------------------------------------------------------------------------------------------------ */

	public void onBackPressed() {
		Log.i("OEA", "Back Pressed...");
		if (receivedId > 0) {
			Intent intent = new Intent(this.getApplicationContext(),
					OutlaysListActivity.class);
			Log.i("OEA", "Starting Activity Outlay List");
			startActivity(intent);
		} else {
			Intent intent = new Intent(this.getApplicationContext(),
					HomeActivity.class);
			Log.i("OEA", "Starting Activity Outlay List");
			startActivity(intent);
		}
	}

	/*------------------------------------------------------------------------------------------------
	 *--------------------------------------CLICKS--------------------------------------------------
	 *------------------------------------------------------------------------------------------------ */

	public void onClick(View v) {
		if (v == btnAccept) {
			Log.i("OEA", "New/Edit Outlay");
			// Inflate the Outlay
			outlay = new Outlay();
			charge = Utilities.stringToInt(edtCharge.getText().toString());
			item = edtItem.getText().toString();
			place = edtPlace.getText().toString();
			album = "";
			/*--------------------------------------FROM CHANGE AUTOGENERATED-----------------------------------------*/
			if (receivedHasChanges) { // Update SaveApp
				addressDesc = receivedAddressDesc;
				date = saveApp.outlay.getDate();
				saveApp.setAddressDesc(receivedAddressDesc);
				saveApp.setLatitude(receivedLatitude);
				saveApp.setLongitude(receivedLongitude);
			}

			/*--------------------------------------FROM DETAIL-----------------------------------------*/
			if (receivedId > 0) {
				outlay.inflate(receivedId);
				outlay.setCharge(charge);
				outlay.setItemDesc(item);
				outlay.setPlaceDesc(place);
				outlay.setAddressId(addressId);
				outlay.setAddressDesc(addressDesc);
				outlay.setDate(date);
				outlay.setNote(note);

				// TODO setAlbum()

				Log.i("OEA", "Updating Outlay...");
				outlay.update();
				saveApp.setCurrentBudget(Utilities.calculateCurrentBudget());
				saveApp.setCurrentDays(Utilities.daysUntilToday(saveApp
						.getStartDate()));

				Bundle bundle = new Bundle();
				bundle.putInt("Id", receivedId);
				Intent intent = new Intent(this.getApplicationContext(),
						OutlayDetailActivity.class);
				intent.putExtras(bundle);
				Log.i("OEA", "Starting Activity Outlay Detail");
				startActivity(intent);

				/*--------------------------------------FROM HOME-----------------------------------------*/
			} else {
				if (!isAdding)
					charge = charge * (-1);

				// Insert
				outlay.insert(saveApp.getAccountId(), charge, date, note, item,
						place, album, addressDesc, longitude, latitude);

				// Recalculate Global Variables
				saveApp.setCurrentBudget(Utilities.calculateCurrentBudget());
				saveApp.setCurrentDays(Utilities.daysUntilToday(saveApp
						.getStartDate()));

				// Jump to List Activity
				Intent intent = new Intent(this.getApplicationContext(),
						OutlaysListActivity.class);
				Log.i("OEA", "Starting Activity Outlay Detail");
				startActivity(intent);
			}

			/* ******************************************************************************** */
		} else if (v == btnNotes) {
			saveState();
			Bundle bundle = new Bundle();
			bundle.putString("Note", saveApp.outlay.getNote());
			Intent intent = new Intent(this.getApplicationContext(),
					NoteActivity.class);
			intent.putExtras(bundle);
			startActivityForResult(intent, 0);

			/* ******************************************************************************** */
		} else if (v == btnFile) {
			saveState();
			Toast.makeText(this,
					"You can not link files in this version. Upgrade Now!",
					Toast.LENGTH_SHORT).show();
			/* ******************************************************************************** */
		} else if (v == btnPhoto) {
			saveState();
			// Intent intent = new Intent(this.getApplicationContext(),
			// PhotoActivity.class);
			// startActivity(intent);
			Toast.makeText(this,
					"You can not save the photo in this version. Upgrade Now!",
					Toast.LENGTH_SHORT).show();
			/* ******************************************************************************** */
		} else if (v == btnAddressChange) {
			saveState();
			Bundle bundle = new Bundle();
			bundle.putInt("Id", receivedId);
			bundle.putBoolean("HasBeenChanged", false);
			Intent intent = new Intent(this.getApplicationContext(),
					ChangeAutogeneratedActivity.class);
			intent.putExtras(bundle);
			startActivity(intent);
			// startActivityForResult(intent, requestCode);
		}
	}

	protected void onActivityResult(int requestCode, int resultCode, Intent data) {
		note = data.getStringExtra("Note");
		saveApp.outlay.setNote(note);
		if (note != null)
			Toast.makeText(this, "Note Added", Toast.LENGTH_SHORT).show();

	}

}
